# Site settings
title: Alex Massaad
email: your-email@domain.com
url: https://amassaad.github.io
description: "Alex Massaad is a magician in Ottawa"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Alex Massaad

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ottawamagician
  - title: facebook
    url: https://www.facebook.com/amassaad
  - title: bitbucket
    url: http://bitbucket.org/massaad
  - title: github
    url: https://github.com/amassaad

# Build settings
markdown: kramdown
permalink: pretty
